apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-s3-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: s3.csi.irbe.dev
  csi:
    driver: s3.csi.irbe.dev
    volumeHandle: <BUCKET-NAME>
    nodePublishSecretRef:
      name: csi-s3
      namespace: default