apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-s3-pvc
spec:
  volumeName: csi-s3-pv
  accessModes:
  - ReadWriteOnce
  storageClassName: s3.csi.irbe.dev
  resources:
    requests:
      storage: 1G