name: test
defaults:
  run:
    shell: bash
on: 
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  unit_test:
    container: golang:1.16-buster
    name: unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: unit test
        run: make test