name: test
defaults:
  run:
    shell: bash
on: 
  push:
    branches:
      - main
jobs:
  unit_test:
    name: unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: unit test
        run: make test